### ISSUE TITLE
Use log levels from rfc5424

### ISSUE THREAD

**Issue by H4ad** [H4ad/nodejs-logging-proposal#2]
At https://datatracker.ietf.org/doc/html/rfc5424#section-6.2.1, page 11.

Suggested by Matteo.

**Comment by H4ad** [comment]
~Blocked by #4~

Unblocked, we can just rewrite the new log levels directly.

**Comment by H4ad** [comment]
@mcollina About this suggestion, these are the log levels:

```
Numerical       Severity
0               Emergency: system is unusable
1               Alert: action must be taken immediately
2               Critical: critical conditions
3               Error: error conditions
4               Warning: warning conditions
5               Notice: normal but significant condition
6               Informational: informational messages
7               Debug: debug-level messages
```

Do you think we should keep the log level number as 0-7? Or even allow the users to customize the log level?

I think we maybe will need to be more opinionated here, so probably sticking with 0-7 and also do not allow new log levels.

**Comment by H4ad** [comment]
About `Facility`, I think we don't need to introduce that multiplication.

**Comment by mcollina** [comment]
Keep them fixed for now.

**Comment by H4ad** [comment]
I updated the current implementation to use these new log levels.

I also added the `silent` with the value `-Infinity`.
